name: security-check
on:
  push:
    branches: [ main ]
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'upload.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
        
  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out main branch
        uses: actions/checkout@v2
          
      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: 'NodeGot'
          createprofile: true
          filepath: 'upload.zip'
          vid: '${{ secrets.VERACODE_ID }}'
          vkey: '${{ secrets.VERACODE_KEY }}'
