name: security-check
on:
  push:
    branches: [ main ]
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Empacotamento dos arquivos
        uses: thedoctor0/zip-release@master
        with:
          filename: 'veracode.zip'
          path: .
      - name: Publicando Artefato
        uses: actions/upload-artifact@v2
        with:
          name: pacoteVeracode
          path: veracode.zip
        
  Veracode_UploadAndScan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artefato
        uses: actions/download-artifact@v2
        with:
          name: pacoteVeracode
      - uses: veracode/veracode-uploadandscan-action@master # Faz a analise da Veracode
        env:
          VeracodeID: ${{ secrets.VERACODE_ID }} # Lembrar de criar as credenciais no Secrets
          VeracodeKey: ${{ secrets.VERACODE_KEY }}
      
        with:
          vid: '$VeracodeID'
          vkey: '$VeracodeKey'
          criticality: 'VeryHigh'
          appname: 'NodeGoat-Demo-will'
          createprofile: true
          filepath: 'veracode.zip'
          deleteIncompleteScan: false
          version: ${{ github.run_id }}
